Compute gramian
JinraeKim/FaultTolerantControl.jl pull request #60
Opened 2022-02-02 12:16 UTC by hnlee77

Resolves https://github.com/JinraeKim/FTCTests.jl/issues/58.

2022-02-02 12:21 UTC, hnlee77 commented
매트랩, 파이썬으로 구현된 [깃헙 코드](https://github.com/gramian/emgr)를 참고하여 julia로 구현한 것으로 깃헙에 구현된 선형 시스템 예제와 동일한 시스템에 대해 동일한 결과가 산출되는 것을 확인함.
### Results
- Controllability Gramian
```
[[0.       0.       0.       0.      ]
 [0.       0.432324 0.       0.432324]
 [0.       0.       0.       0.      ]
 [0.       0.432324 0.       0.432324]]
```
- Observability Gramian
```
[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.43802594 0.43802594]
 [0.         0.         0.43802594 0.43802594]]
```

2022-02-02 23:49 UTC, JinraeKim commented
전반적으로 indent 간격이 들쭉날쭉하거나 너무 넓은데, space 4개로 통일할 수 있을까요?

2022-02-03 03:02 UTC, hnlee77 commented
> 전반적으로 indent 간격이 들쭉날쭉하거나 너무 넓은데, space 4개로 통일할 수 있을까요?

오잉 그러네요???! 이거 제 편집기에서는 space 4개로 되어있긴 한데... 일단 수정을 해보겠습니다.

2022-02-03 03:34 UTC, hnlee77 commented
@JinraeKim 수정했습니다 ㅎㅎ

2022-02-03 03:46 UTC, JinraeKim reviewed
`empirical_ctrl_gramian` 이랑 `epmirical_obsv_gramian` 이랑 구조가 상당히 유사해보이네요.
하나의 함수 `_empirical_gramian` 를 작성하여 각 함수에서 불러오는건 어떤가요?

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +    M, N, L = s
```suggestion
function empirical_ctrl_gramian(f, M::Int, N::Int, L::Int; dt::Real, tf::Real, pr::Matrix, xs::Vector)
```

인자를 직접 받는게 좋을 것 같습니다 (`s` 가 특정되지 않아서)

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +                    Wc = Wc .+ x * x'  # Question(why is this different dot(x, x')?)
이거 무슨 의미로 쓰여진 코멘트이죠?

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +    M, N, L = s
여기도

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +function ssp2(f, g, dt, tf, x0, u, p; STAGES=3)
f, g 의 형태를 특정하거나, f, g 의 형태를 적어도 docs 에 기입하기

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +    nt = Int(floor(tf / dt) + 1)
`nt` 가 2보다 작으면 어떻게 되나요?

2022-02-03 03:46 UTC, JinraeKim commented on src/gramian.jl
> +    nt = Int(floor(tf / dt) + 1)
`dt` 는 항상 양수? `tf` 는 항상 `dt`보다 큰가?
이런거를 assertion 처리해주면 좋을듯~

2022-02-03 05:42 UTC, hnlee77 commented on src/gramian.jl
> +                    Wc = Wc .+ x * x'  # Question(why is this different dot(x, x')?)
이거 말 그대로인데 dot(x, x')과 값이 다른데 이유를 잘 모르겠습니다.

2022-02-03 05:54 UTC, hnlee77 commented on src/gramian.jl
> +    nt = Int(floor(tf / dt) + 1)
굳~

2022-02-03 09:40 UTC, JinraeKim commented on src/gramian.jl
> +                    Wc = Wc .+ x * x'  # Question(why is this different dot(x, x')?)
어... 원하는 값이 x 와 x' 의 내적인가요?

제가 봤을 때는 당연히 다를 것 같은데... 어떤 값을 원하는건가요?

2022-02-03 09:44 UTC, JinraeKim requested changes
혹시 현재 스크립트 내용을 `{src,test}/reconfigurability.jl` 로 넣는 것은 어떨까요?
귀찮게 해서 죄송합니다 ㅎㅎ...

2022-02-03 09:44 UTC, JinraeKim commented on src/gramian.jl
> +A function for Low-Storage Strong-Stability-Preserving Second-Order Runge-Kutta.
혹시 참고문헌 같은거 있을까요? 링크나?

2022-02-03 09:44 UTC, JinraeKim commented on src/gramian.jl
> +A function for computation of controllability or observability gramian.
혹시 참고문헌 같은거 있을까요? 링크나?

2022-02-03 13:10 UTC, hnlee77 commented on src/gramian.jl
> +                    Wc = Wc .+ x * x'  # Question(why is this different dot(x, x')?)
내적을 구하고 싶었으나 x*x'의 결과가 파이썬에서의 내적과 같은 값이 나옵니다. 그래서 이렇게 작성하였으나.. 왜 다른지 잘 모르겠습니다.

2022-02-03 13:19 UTC, hnlee77 commented on src/gramian.jl
> +A function for Low-Storage Strong-Stability-Preserving Second-Order Runge-Kutta.
참고문헌 추가했습니다요~

2022-02-03 13:48 UTC, hnlee77 commented
> 혹시 현재 스크립트 내용을 `{src,test}/reconfigurability.jl` 로 넣는 것은 어떨까요? 귀찮게 해서 죄송합니다 ㅎㅎ...
> 
> 내용은 좋습니다요~

이 내용을 반영했습니다~ `test/reconfigurability.jl`과 같이 넣으면 되는지 한번 봐주세요.

2022-02-04 05:33 UTC, JinraeKim commented
@hnlee77
테스트를 구분해주시면 좋을듯~
[Convex.jl 의 예시](https://github.com/jump-dev/Convex.jl/blob/master/test/test_utilities.jl#L22) 를 참고해주세요

2022-02-04 05:42 UTC, hnlee77 commented
> @hnlee77 테스트를 구분해주시면 좋을듯~ [Convex.jl 의 예시](https://github.com/jump-dev/Convex.jl/blob/master/test/test_utilities.jl#L22) 를 참고해주세요

테스트 구분했습니다. 예시 감사합니다.

2022-02-07 05:39 UTC, JinraeKim commented on test/reconfigurability.jl
> +    @test Wc !== nothing && Wo !== nothing
```suggestion
    @test Wc != nothing && Wo != nothing
```

[=== 와 ==의 차이](https://stackoverflow.com/questions/38601141/what-is-the-difference-between-and-comparison-operators-in-julia/38602012) 참고. 사실 현재 맥락에서는 !== 로 쓰나 != 로 쓰나 비슷할 것이긴 한데, 일단 != 로 하는게 좋을 것 같아요

2022-02-07 05:40 UTC, JinraeKim commented on test/reconfigurability.jl
> +    @test Wc !== nothing && Wo !== nothing
이거 하고 머지하시면 될듯!

2022-02-07 06:14 UTC, hnlee77 commented
@JinraeKim approve 해주세여

2022-02-07 06:28 UTC, JinraeKim approved these changes

2022-02-07 06:32 UTC, merged